### ISSUE TITLE
Firebase Authentication?

### ISSUE THREAD

**Issue by se1exin** [rlamasb/Firebase.Xamarin#1]
Hi, I can see that it this is based on https://github.com/step-up-labs/firebase-database-dotnet, but step-up-labs has another repo for Auth (https://github.com/step-up-labs/firebase-database-dotnet), wondering has this been implemented Firebase.Xamarin in any way? 

I've browsed the code but just want to make sure I haven't simply overlooked it. Let me know if it has not been added and I'll get started on a fork to integrate it in.

**Comment by palote2015** [comment]
I just saw this repo now and I have come for the same reason: "Firebase Auth". I will wait for the reply

**Comment by se1exin** [comment]
I'm pretty certain that it Firebase.Xamarin does not include Auth. I'm going to implement it this evening after work. Will keep you posted @palote2015

**Comment by rlamasb** [comment]
Hi guys,

I have implemented the Token generation functionality. 

Once you generate the Token you can pass it as parameter to the client.

Please have a look and tell me what you think.

**Comment by se1exin** [comment]
Thanks @rlamasb I'll check it out as it will definitely come in handy, however this appears to be only for custom Firebase Authentication types (unless I have missed something?).

My use case requires Firebase Email/Password authentication as I am managing my Users directly in Firebase (see https://firebase.google.com/docs/auth/android/password-auth) v3. Additionally, Firebase's third party OAuth providers would be very handy (Google, Facebook, Twitter, GitHub).

**Comment by rlamasb** [comment]
Hi @se1exin, you are absolutely right this is just for custom Authentication. 

I have not implemented the remaining ones as I am currently in delivery phase of a project and time is not on my side atm.
If you want to implement the other providers that would be awesome.

**Comment by se1exin** [comment]
@rlamasb @palote2015 Pull #2 has all the supported Auth methods from https://github.com/step-up-labs/firebase-authentication-dotnet

**Comment by palote2015** [comment]
Thanks @rlamasb @se1exin for all!!, I'll try it.

**Comment by rlamasb** [comment]
That is great @se1exin, just thanks for your help.
